name: SearchAndDestroy
version: 0.1
description: In Search and Destroy you can play CS:GO and CoD in one game. Plant the bomb / Defuse the bomb! (Devathlon project)
main: com.muwbi.devathlon.SearchAndDestroy
authors: [Muwbi, Gelox_, ploxh, Tropadeira]
depend: [Yamler]
commands:
  gamestate:
    description: Change the gamestate
    usage: /<command>
